<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta() ?>
        <meta http-equiv="Pragma" content="no-cache">
            <meta http-equiv="expires" content="0">
                <link rel="shortcut icon" href="<?php echo STATIC_URL ?>favicon.ico" />
                <!-- css -->
                <link href="<?php echo STATIC_URL ?>css/realtones/wap/general.css"
                      rel="stylesheet" />
                <link href="<?php echo STATIC_URL ?>css/realtones/basico240.css"
                      rel="stylesheet" />
                </head>
                <body>
                    <div id="titulo" class="clearfix">

                        <div class="titulo-pagina">WAP ENTEL</div>
                    </div>
                    <br/>
                    <?= $this->layout()->content ?>
                    <br>
                        <!--Footer-->                                

                        <br>
                            <table class="artist-photo">
                                <tr>
                                    <td class="artist" style="background-color: #0073ae">
                                        <div class="artist-text">
                                            <div class="title-img">
                                                <a class="text-title" style="color: white;font-size:15px;" href="/pe/realtones/legal">
                                                    LEGAL
                                                </a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            </table>
                            <!--/Footer-->
                            </body>
                            </html>