<div data-role="content">   
    <br>
    <div class='inset'>
        <div> 
            <img width="100%"   src="<?php echo STATIC_URL ?>css/jqueryMobile/banner_dedicatorias_nextel2.gif">
        </div>
        <!-- <ul data-role="listview" data-inset="false" data-icon="false" data-divider-theme="b">
             <li><a href="#" style="color:white;background-color: #FF6702;">
        <?php
        $nombre_fichero = APPLICATION_PATH . '/../public/dinamic/fulltracks/basico360/musica/' . $this->catalogo . '.jpg';
        if (file_exists($nombre_fichero)) {
            ?>
                             <img 
                                 src="<?php echo DINAMIC_URL ?>fulltracks/basico360/musica/<?= $this->catalogo ?>.jpg"  width="150" height="150"><?php } else {
            ?>
                             <img src="<?php echo DINAMIC_URL ?>fulltracks/basico360/musica/default.gif" width="150" height="150" border="0" />
     
        <?php }
        ?>
                     <h2><?= strtoupper($this->tema) ?></h2>
                     <p><?= $this->artista ?></p>
                     <p class="ui-li-aside"><strong></strong></p>
                 </a>
             </li>
         </ul>-->
        <div class='message info'>
            <i class='fa fa-lightbulb-o' style="color: white"></i>
            <!--<p style="color: white">Bienvenido, estas suscrito al servicio de Dedicatorias</p>-->
            <p style="color: white">Bienvenido al servicio de DEDICATORIAS ENTEL. Para elegir la cancion que deseas dedicar, dale click en Aceptar.</p>
        </div>
    </div>
    <!----------------TONOS------------------------------------->
    <?php if ($this->perfil == 1) {
        ?>
        <td class="artist" style="background-color: orange" >
            <div class="artist-text">
                <div class="title-img">
                    <a class="text-title" style="background-color: orange;color: white;font-size:18px"
                       href="/pe/realtones/confirmar-descarga?catalog=<?php echo $this->catalogo; ?>&descargar=true">ACEPTAR
                    </a>
                </div>
            </div>
        </td>
    <?php } else { ?>
        <form data-ajax="false" action="<?php echo $this->action; ?>"  method="post" Enctype="multipart/form-data">
            <ul data-role="listview" data-inset="true">
                <li>
                    <input type="hidden" value="1"  name="mensaje"/>
                    <button style="background-color: #FF6702;color:white" type="submit" ><i class='lIcon fa fa-check'></i>Aceptar</button>
                </li>
            </ul>
        </form>

    <?php } ?>
</div>