<div data-role="content">   
    <img width="100%" height="50%" src="<?php echo STATIC_URL ?>css/jqueryMobile/artista/destacado.jpg"  border="0" />
    <div class='inset'>
        <ul data-role="listview" data-inset="false" data-icon="false" data-divider-theme="b">
            <!--            <li><a href="#" style="color:black;background-color: #EEEEEE;">
            <?php
            $nombre_fichero = APPLICATION_PATH . '/../public/dinamic/fulltracks/basico360/musica/' . $this->catalogo . '.jpg';
            if (file_exists($nombre_fichero)) {
                ?>
                                                <img 
                                                    src="<?php echo DINAMIC_URL ?>fulltracks/basico360/musica/<?= $this->catalogo ?>.jpg"  width="150" height="150"><?php } else {
                ?>
                                                <img src="<?php echo DINAMIC_URL ?>fulltracks/basico360/musica/default.gif" width="150" height="150" border="0" />
                        
            <?php }
            ?>
                                <h2><?= strtoupper($this->tema) ?></h2>
                                <p><?= $this->artista ?></p>
                                <p class="ui-li-aside"><strong></strong></p>
                            </a>
                        </li>-->
            <li style="color:black;background-color: white;">
                <h2><?= strtoupper($this->tema) ?></h2>
                <p><?= $this->artista ?></p>
                <p class="ui-li-aside"><strong style="color: #FF6702;" >S/.5.00</strong></p>
            </li>
        </ul>
        <div class='message info'>
            <i class='lightbulb-o'> <img src="<?php echo STATIC_URL ?>css/jqueryMobile/images/icons-png/audio-white.png" border="0" />
            </i>
            <p style="color: white">Esta seguro que desea la dedicatoria elegida ?.</p>
        </div>
    </div>
    <!----------------TONOS------------------------------------->
    <?php if ($this->perfil == 1) {
        ?>
        <td class="artist" style="background-color: orange" >
            <div class="artist-text">
                <div class="title-img">
                    <a class="text-title" style="background-color: orange;color: white;font-size:18px"
                       href="/pe/realtones/confirmar-descarga?catalog=<?php echo $this->catalogo; ?>&descargar=true">ACEPTAR
                    </a>
                </div>
            </div>
        </td>
    <?php } else { ?>
        <form action="<?php echo $this->action; ?>"  method="post" Enctype="multipart/form-data">
            <ul data-role="listview" data-inset="true">
                <input type="hidden" name="catalogo" value="<?php echo $this->catalogo; ?>">
                <input type="hidden" name="descargar" value="true">

                <li>
                    <button type="submit" style="background-color: #FF6702;color:white" ><i class='lIcon fa fa-check'></i>Aceptar</button>
                    <div>
                        <a href='#' data-rel='back' style="background-color: #FF6702;color:white" data-role='button' ><i class='lIcon fa fa-times'></i>Cancelar</a>
                    </div>
                </li>
            </ul>

        </form>

    <?php } ?>
</div>