<div data-role="content">  
    <div class='inset' style="color:black;text-align:justify">
        <h2>1. Aceptaci&oacute;n de Condiciones</h2>
        <p>
            La utilizaci&oacute;n de los servicios aqu&iacute; ofrecidos implica la aceptaci&oacute;n y pleno conocimiento de las siguientes condiciones de uso aqu&iacute; indicadas.
            Por favor lea estas condiciones de uso detenidamente. Si no est&aacute; de acuerdo con estas condiciones de uso, abst&eacute;ngase de utilizar o adquirir los servicios que aqu&iacute; se ofrecen.
        </p>
        <h2>2. El Servicio</h2>
         <p>
            Mobile Solutions ofrece a trav&eacute;s de este portal wap, servicios para celulares, entre los cuales se encuentran servicios de SMS y Multimedia. 
            Los Productos y servicios ofrecidos son &uacute;nica y exclusivamente para usuarios de Entel Perú.
        </p>
        <h2>3. Modalidad</h2>
        <p>
            Todos los servicios se ofrecen en modalidad de suscripci&oacute;n y demanda.
            Antes de contratar cualquier tipo de Servicio, lea cuidadosamente las instrucciones para la contrataci&oacute;n de los mismos, a fin de verificar que su tel&eacute;fono celular sea compatible para el servicio que desea contratar.
        </p>
        <h2>4. Tarifas</h2>
        <p>
            Las tarifas pueden variar de acuerdo a los productos y/o servicios que desee adquirir.
        </p>
        <h2>5. Celulares Soportados</h2>
        <p>
            Todos los equipos 3G de Entel y planes Entel + a nivel nacional.
        </p>
        <h2>6. Forma de Pago</h2>
        <p>
            Para productos contrato los montos se facturan de manera adicional al cargo fijo mensual del Usuario. Para productos prepago, los precios por la suscripción le serán debitados al Usuario por el operador telefónico directamente del saldo de su tarjeta prepago.
        </p>
        <h2>7. Contacto</h2>
        <p>
            <a href="mailto:servicioalcliente@moso.pe">servicioalcliente@moso.pe</a>
        </p>
    </div>
</div>