<div data-role="content">   
    <!--<br>-->
    <div  style="margin: 5px">
<!--        <div> 
            <img width="100%"   src="<?php echo STATIC_URL ?>css/jqueryMobile/banner_dedicatorias_nextel2.gif">
        </div>-->
        
            <a href="/pe/dedicatorias/suscripcion"><img width="100%" src="<?php echo STATIC_URL ?>css/jqueryMobile/banner_serenatas.gif"></a>
        
    </div>
</div>