<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
          <link rel="shortcut icon" href="<?php echo STATIC_URL ?>favicon.ico" />
    </head>

    <div id="prueba_master" class="wlp-bighorn-book">
        <div class="wlp-bighorn-book-content">
            <div class="wlp-bighorn-layout wlp-bighorn-layout-flow">
                <div class="wlp-bighorn-layout-cell wlp-bighorn-layout-flow-horizontal wlp-bighorn-layout-flow-first" style="width: 100%">
                    <!----------------BANNER DE DEDICATORIA------------------------------------->

                    <div> 
                        <a href="">
                            <img width="100%" src="<?php echo STATIC_URL ?>img/entel_avatar.jpg">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>

    <!--/Footer-->
</body>
</html>
