<div id="prueba_master" class="wlp-bighorn-book">
    <div class="wlp-bighorn-book-content">
        <div class="wlp-bighorn-layout wlp-bighorn-layout-flow">
            <div class="wlp-bighorn-layout-cell wlp-bighorn-layout-flow-horizontal wlp-bighorn-layout-flow-first" style="width: 100%">

                <table class="artist-photo">
                    <tr>
                        <td class="artist">
                            <?php
                            $nombre_fichero = APPLICATION_PATH . '/../public/dinamic/fulltracks/basico360/musica/' . $this->catalogo . '.jpg';
                            if (file_exists($nombre_fichero)) {
                                ?>
                                <img class="img-icono"
                                     src="<?php echo DINAMIC_URL ?>fulltracks/basico360/musica/<?= $this->catalogo ?>.jpg"><?php } else {
                                ?>
                                <img src="<?php echo DINAMIC_URL ?>fulltracks/basico360/musica/default.png" width="64" height="47" border="0" />

                            <?php }
                            ?>
                        </td>
                        <td class="artistaDestacado" colspan=2>
                            <div class="artistaDestacadoDetalle">
                                <a href="#"><span><?= strtoupper($this->tema) ?></span><p><?= $this->artista ?></p>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="artist"  colspan=2 >
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title" style="color: black;font-size:18px"
                                       href="#">Desea confirmar la descarga?
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>

                <br>
                <!----------------TONOS------------------------------------->
                <table class="artist-photo">
                    <tr>
                        <?php if ($this->perfil == 1) {
                            ?>
                            <td class="artist" style="background-color: orange" >
                                <div class="artist-text">
                                    <div class="title-img">
                                        <a class="text-title" style="background-color: orange;color: white;font-size:18px"
                                           href="/pe/fulltracks/confirmar-descarga?catalog=<?php echo $this->catalogo; ?>&descargar=true">ACEPTAR
                                        </a>
                                    </div>
                                </div>
                            </td>
                        <?php } else { ?>
                            <td class="artist"  colspan=2 style="background-color: orange">
                                <form action="<?php echo $this->action; ?>"  method="post" Enctype="multipart/form-data">
                                    <input type="hidden" name="catalogo" value="<?php echo $this->catalogo; ?>">
                                    <input type="hidden" name="descargar" value="true">
                                    <div class="artist-text">
                                        <div class="title-img">
                                            <button style="border:none;background-color: orange;color: white;font-size:18px" type="submit">ACEPTAR
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </td>
                        <?php } ?>
                    </tr>
                    <tr>
                        <td class="artist"  colspan=2 style="background-color: orange">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title" style="color: white;font-size:18px"
                                       href="/pe/fulltracks">CANCELAR
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>

                </table>
            </div>
        </div>
    </div>
</div>