<div id="prueba_master" class="wlp-bighorn-book">
    <div class="wlp-bighorn-book-content">
        <div class="wlp-bighorn-layout wlp-bighorn-layout-flow">
            <div class="wlp-bighorn-layout-cell wlp-bighorn-layout-flow-horizontal wlp-bighorn-layout-flow-first" style="width: 100%">
                <link href="<?php echo STATIC_URL ?>css/fulltracks/estilogGeneral.css"
                      rel="stylesheet" type="text/css" media="all" />
                <!----------------TONOS------------------------------------->
                 <a  id="cabecera_paso1" class="paso primero seleccionado" href="/pe/realtones/mis-compras">
                        <span style="font-weight:bold;float: right;border:none;background-color: transparent !important; color:   #0073ae;font-size: 4vw;
                              margin-top:0;text-decoration:none;font-size: 4vw; margin-right: 10px">VER MIS COMPRAS</span>
                    </a>
                <br>
                <?php $this->getMesseger(); ?>
                <table class="artist-photo">
                    <tr>
                        <td class="artist">
                            <img class="img-icono"
                                 src="<?php echo DINAMIC_URL ?>realtones/avanzado/tonos/destacado.jpg">
                        </td>
                        <td class="artistaDestacado" colspan=2>
                            <div class="artistaDestacadoDetalle">
                                <span><?= strtoupper($this->SoapTonos[0]->tema) ?></span>
                                <form action="/pe/realtones/confirmar-descarga"  method="post" Enctype="multipart/form-data">
                                    <input type="hidden" name="catalogo" value="<?= $this->SoapTonos[0]->catalogo ?>">
                                    <input type="hidden" name="artista" value="<?= $this->SoapTonos[0]->artista ?>">
                                    <input type="hidden" name="tema" value="<?= $this->SoapTonos[0]->tema ?>">
                                    <br>
                                    <p><button style="border:none;background-color: transparent !important; color:   #0073ae;font-size: 4vw;
                                               margin-top:0;text-decoration:none;" type="submit"><?= $this->SoapTonos[0]->artista ?>
                                        </button></p>
                                </form>  

                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="artist" colspan=3 >
                            <div class="artist-text">

                                <div class="title-img">
                                    <a class="text-title"
                                       href="">Descarga los mejores TONOS en tu celular y personaliza tus llamadas. Costo semanal: S/.4.90  Incluye 1 TONO
                                        . Costo adicional por más descargas dentro de la semana: s/.2.50 .
                                        Para Cancelar envía SALIR al 4556 .
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
                <br>
                <table class="artist-photo">
                    <tr>
                        <td class="artist" colspan=5 style="background-color: orange;">
                            <div class="artist-text">

                                <div class="title-img">
                                    <a class="text-title" style="font-weight:bold;color: white;font-size:17px"
                                       href="">TOP 10
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <?php
                        $i = 0;
                        foreach ($this->SoapTonos as $item):
                            $i++;
                            if ($i > 1 && $i <= 6) {
                                ?>
                                <td class="artist">
                                    <div class="artist-text">
                                        <!--<span class="puestoRed"><p></p></span>-->
                                        <div>
                                            <img class="img-icono"
                                                 src="<?php echo DINAMIC_URL ?>realtones/avanzado/tonos/artista_1.gif">
                                        </div>
                                        <div class="title-img">
                                            <form action="/pe/realtones/confirmar-descarga"  method="post" Enctype="multipart/form-data">
                                                <input type="hidden" name="catalogo" value="<?= $item->catalogo ?>">
                                                <input type="hidden" name="artista" value="<?= $item->artista ?>">
                                                <input type="hidden" name="tema" value="<?= $item->tema ?>">
                                                <br>
                                                <span><button style="border:none;background-color: transparent !important;color: black;font-size:9px" type="submit"><?= strtoupper($item->tema) ?>
                                                    </button></span>
                                            </form>

                                        </div>
                                    </div>
                                </td>
                                <?php
                            }
                        endforeach;
                        ?> 
                    </tr>
                    <tr>
                        <td class="artist" colspan=5 >
                            <div class="artist-text">
                            </div>
                        </td>
                    </tr>
                    <tr>
                         <?php
                        $j = 5;
                        foreach ($this->SoapTonos as $item):
                            ++$j;
                            if ($j >11 && $j <= 19) {
                                ?>
                                <td class="artist">
                                    <div class="artist-text">
                                        <!--<span class="puestoRed"><p><?= $i - 1 ?></p></span>-->
                                        <div>
                                            <img class="img-icono"
                                                 src="<?php echo DINAMIC_URL ?>realtones/avanzado/tonos/artista_1.gif">
                                        </div>
                                        <div class="title-img">
                                            <form action="/pe/realtones/confirmar-descarga"  method="post" Enctype="multipart/form-data">
                                                <input type="hidden" name="catalogo" value="<?= $item->catalogo ?>">
                                                <input type="hidden" name="artista" value="<?= $item->artista ?>">
                                                <input type="hidden" name="tema" value="<?= $item->tema ?>">
                                                <br>
                                                <span><button style="border:none;background-color: transparent !important;color: black;font-size:9px" type="submit"><?= strtoupper($item->tema) ?>
                                                    </button></span>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                                <?php
                            }
                        endforeach;
                        ?> 
                    </tr>
                </table>
                <br>
            </div>
        </div>
    </div>
</div>
