<div id="prueba_master" class="wlp-bighorn-book">
    <div class="wlp-bighorn-book-content">
        <div class="wlp-bighorn-layout wlp-bighorn-layout-flow">
            <div class="wlp-bighorn-layout-cell wlp-bighorn-layout-flow-horizontal wlp-bighorn-layout-flow-first" style="width: 100%">
                <table class="artist-photo" >
                    <tr>
                        <td class="artistaDestacado" style="text-align:justify; color: black">
                            <p><b>1. Aceptaci&oacute;n de Condiciones</b><br/>
                                La utilizaci&oacute;n del servicio aqu&iacute; ofrecido atribuye la condición de Usuario e implica la aceptación de las Condiciones Legales aquí indicadas.
                            </p>
                            <p><b>2. El Servicio</b><br/>
                                El servicio FullTracks permite al usuario descargar todas las canciones completas que est&eacute;n disponibles en este portal sin costo.
                            </p>
                            <p><b>3. Modalidad</b><br/>
                                El servicio se ofrece en modalidad de suscripci&oacute;n. El usuario se suscribe al servicio enviando el comando F al 4556. El sistema lo suscribir&aacute; y le enviar&aacute; un link para que ingrese al portal de FullTracks y elija las canciones que desee descargar. Haciendo clic en la canci&oacute;n se realiza la descarga autom&aacute;tica de la misma. Cada d&iacute;a se le enviar&aacute; el link para que ingrese al portal y descargue las canciones que desee y pueda hasta que el usuario solicite la cancelaci&oacute;n del servicio. Para cancelar el servicio el usuario debe enviar un mensaje de texto con la palabra SALIR al 4556.
                            </p>
                            <p><b>4. Tarifas</b><br/>
                                Costo diario:  S/1.65 inc. IGV. El usuario puede descargarse todas las canciones que desee pagando una sola tarifa diaria.
                            </p>
                            <p><b>5. Celulares Soportados</b><br/>
                                Todos los equipos 3G de Entel y planes Entel + a nivel nacional.
                            </p>
                            <p><b>6. Forma de Pago</b><br/>
                                Para productos contrato los montos se facturan de manera adicional al cargo fijo mensual del Usuario. Para productos prepago, los precios por la suscripción le serán debitados al Usuario por el operador telefónico directamente del saldo de su tarjeta prepago.
                            </p>
                            <p><b>7. Contacto</b><br/>
                                <a href="mailto:servicioalcliente@mobilesolutions.pe">servicioalcliente@mobilesolutions.pe</a>
                            </p>

                            <div style="clear:both"></div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>