<div id="prueba_master" class="wlp-bighorn-book">
    <div class="wlp-bighorn-book-content">
        <div class="wlp-bighorn-layout wlp-bighorn-layout-flow">
            <div class="wlp-bighorn-layout-cell wlp-bighorn-layout-flow-horizontal wlp-bighorn-layout-flow-first" style="width: 100%">
                <!----------------BANNER DE DEDICATORIA------------------------------------->
                <?php $this->getMesseger(); ?>
                <table class="artist-photo">
                    <tr>
                        <td class="artist">
                            <?php
                            $nombre_fichero = APPLICATION_PATH . '/../public/dinamic/fulltracks/basico360/musica/' . $this->SoapMusica[0]->catalogo . '.jpg';
                            if (file_exists($nombre_fichero)) {
                                ?>
                                <img class="img-icono"
                                     src="<?php echo DINAMIC_URL ?>fulltracks/basico360/musica/<?= $this->SoapMusica[0]->catalogo ?>.jpg" ><?php } else {
                                ?>
                                <img src="<?php echo DINAMIC_URL ?>fulltracks/basico360/musica/default.png" width="64" height="47" border="0" />

                            <?php }
                            ?>
                        </td>
                        </tr>
                        <tr>
                        <td class="artistaDestacado" colspan=2>
                            <div class="artist-text" style="text-align:left;">
                                        <div class="title-img">
                                            <a class="text-title"
                                               href="/pe/fulltracks/confirmar-descarga?catalogo=<?= $this->SoapMusica[0]->catalogo ?>"><span><?= strtoupper($this->SoapMusica[0]->tema) ?></span><p style="color: blue"><?= $this->SoapMusica[0]->artista ?></p>
                                            </a>
                                        </div>
                                    </div>
                            
<!--                            <div class="artistaDestacadoDetalle">
                                <a href="#"><span><?= strtoupper($this->SoapMusica[0]->tema) ?></span><p><?= $this->SoapMusica[0]->artista ?></p>
                            </div>-->
<!--                            <div class="artistaDestacadoDetalle">
                                <form action="/pe/fulltracks/confirmar-descarga"  method="post" Enctype="multipart/form-data">
                                    <input type="hidden" name="catalogo" value="<?= $this->SoapMusica[0]->catalogo ?>">
                                    <input type="hidden" name="artista" value="<?= $this->SoapMusica[0]->artista ?>">
                                    <input type="hidden" name="tema" value="<?= $this->SoapMusica[0]->tema ?>">
                                    <span><button style="border:none;background-color: transparent !important; color:   #0073ae;font-size: 4vw;
                                                  margin-top:0;text-decoration:none;" type="submit"><?= strtoupper($this->SoapMusica[0]->tema) ?>
                                        </button></span>
                                </form>  
                            </div>-->
                        </td>
                    </tr>
                    <tr>
                        <td class="artist" colspan=3 >
                            <div class="artist-text">

                                <div class="title-img">
                                    <a class="text-title" style="font-size:10px"
                                       href="">Bienvenido desde hoy podrás descargar toda la música que puedas. Costo: S/1.65 diario. Para cancelar envía un SMS con la palabra SALIR al 4556
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
                <br>
                <!----------------TONOS------------------------------------->

                <table class="artist-photo">
                    <tr>
                        <td class="artist"  colspan=2 style="background-color: orange">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title" style="color: white;font-size:18px"
                                       href="#">MUSICA
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php
                    $i = 0;
                    foreach ($this->SoapMusica as $item):
                        $i++;
                        if ($i > 1 && $i <= 11) {
                            ?>
                            <tr>
                                <td class="artist" >
                                    <div class="artist-text" style="text-align:left;">
                                        <div class="title-img">
                                            <a class="text-title"
                                               href="/pe/fulltracks/confirmar-descarga?catalogo=<?= $item->catalogo ?>"><?= strtoupper($item->tema) ?>
                                            </a>
                                        </div>
                                    </div>
<!--                                    <div class="artist-text" style="text-align:left;">
                                        <div class="title-img">
                                            <form action="/pe/fulltracks/confirmar-descarga"  method="post" Enctype="multipart/form-data">
                                                <input type="hidden" name="catalogo" value="<?= $item->catalogo ?>">
                                                <input type="hidden" name="artista" value="<?= $item->artista ?>">
                                                <input type="hidden" name="tema" value="<?= $item->tema ?>">
                                                <br>
                                                <span><button style="border:none;background-color: transparent !important;color: black;font-size:12px" type="submit"><?= strtoupper($item->tema) ?>
                                                    </button></span>
                                            </form>
                                        </div>
                                    </div>-->
                                </td>
                            </tr>
                            <?php
                        }
                    endforeach;
                    ?> 
                </table>
            </div>
        </div>
    </div>
</div>
